version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Build started at `date`"
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo "Build completed at `date`"
artifacts:
  files:
    - target/myapp.war
    - appspec.yml
    - 'scripts/*'
  discard-paths: no
cache:
  paths:
    - '/root/.m2/**/*'